//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.net_MVC_TP_8_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Num_Art { get; set; }
        public string Desig_Art { get; set; }
        public Nullable<decimal> PU_Art { get; set; }
        public Nullable<int> QttEnStock { get; set; }
        public Nullable<int> SeuilMin { get; set; }
        public Nullable<int> SeuilMax { get; set; }
    }
}
